import type { NextPage } from 'next'
import Head from 'next/head'

import HeaderUi from '../comps/HeaderUi'

const Home: NextPage = () => {
    return (
        <div className='main-body'>
          <Head>
              <title>Warren Chen</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/w.svg" />
          </Head>
          <HeaderUi/>
          <div className='container80'>
              <div className='maincont'>
                <h1>W</h1>
              </div>      

          </div>
          <footer className='foot'>
            <div className='container80'>
              <p>&copy; 2022 Warren Chen</p>

            </div>
          </footer>
        </div>
    )
}

export default Home
