import type { NextPage } from 'next'
import Head from 'next/head'

import HeaderUi from '../comps/HeaderUi'
import MainUi from '../views/MainUi'
import Projects from '../views/Projects'
import About from '../views/About'
import Contact from '../views/Contact'
import FooterUi from '../comps/FooterUi'

const Home: NextPage = () => {
    return (
        <div className='main-body'>
          <Head>
              <title>Warren Chen</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/w.svg" />
          </Head>

          <div className='container80'>
            <HeaderUi/>
          </div>

          <div className='container80'>
              <div className='maincont'>
                <div className='divider'></div>
                <div id='home'>
                  <MainUi/>
                </div>
                <div className='divider'></div>
                <div id='projects'>
                  <Projects/>
                </div>
                <div className='divider'></div>
                <div id='about'>
                  <About/>
                </div>
                <div className='divider'></div>
                <div id='contact'>
                  <Contact/>
                </div>
                <div className='divider border-line-bottem'></div>
              </div>      
          </div>

          <FooterUi/>

          
        </div>
    )
}

export default Home
